#!/bin/bash
set -e

SERVER_TAG=$1

if [ -z "$SERVER_TAG" ]; then
  echo "Usage: ./deploy-server.sh <server-tag>"
  exit 1
fi

export SERVER_TAG=$SERVER_TAG
REGION="ap-northeast-2"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/config"
ENV_FILE="$SCRIPT_DIR/.env"

echo "=========================================="
echo "  SW Campus Server Deployment"
echo "=========================================="
echo "Server Image Tag: $SERVER_TAG"
echo ""

# 설정 디렉토리 생성
mkdir -p $CONFIG_DIR

# 시크릿 가져오기 함수
fetch_secret() {
  local secret_name=$1
  aws secretsmanager get-secret-value \
    --secret-id "$secret_name" \
    --query SecretString \
    --output text \
    --region $REGION
}

# .env 파일 초기화
echo "# Auto-generated by deploy-server.sh" > $ENV_FILE
echo "SERVER_TAG=$SERVER_TAG" >> $ENV_FILE

# JSON을 .env 파일에 추가하는 함수
append_secrets_to_env() {
  local secret_name=$1
  local secret_json=$(fetch_secret "$secret_name")

  while IFS='=' read -r key value; do
    echo "$key=$value" >> $ENV_FILE
    echo "  ✓ $key"
  done < <(echo "$secret_json" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"')
}

echo "[1/6] Loading server secrets..."
append_secrets_to_env "/sw-campus/prod/server"

echo ""
echo "[2/6] Loading database secrets..."
append_secrets_to_env "/sw-campus/prod/db"

echo ""
echo "[3/6] Loading AWS secrets..."
append_secrets_to_env "/sw-campus/prod/aws"

echo ""
echo "[4/6] Loading OAuth secrets..."
append_secrets_to_env "/sw-campus/prod/oauth"

echo ""
echo "[5/6] Loading Google Analytics credentials..."
fetch_secret "/sw-campus/prod/google-analytics" > $CONFIG_DIR/ga-credentials.json
echo "  ✓ ga-credentials.json"

echo ""
echo "=========================================="
echo "  All secrets loaded to .env"
echo "=========================================="

echo ""
echo "[6/6] Deploying containers..."

cd $SCRIPT_DIR

# 기존 컨테이너 정리
echo "Stopping existing containers..."
docker-compose down 2>/dev/null || true

# Pull latest images
echo "Pulling images..."
docker-compose pull

# Deploy
echo "Starting services..."
docker-compose up -d

# Check status
sleep 10
echo ""
echo "=== Service Status ==="
docker-compose ps

echo ""
echo "=== Server Logs (last 30 lines) ==="
docker-compose logs --tail 30 server

echo ""
if docker-compose ps | grep -q "sw-campus-server.*Up"; then
  echo "✅ Deployment successful!"
else
  echo "❌ Deployment failed!"
  exit 1
fi
