# Podman Compose for SW Campus Local Development
# Usage: podman-compose -f podman-compose.yml up -d

services:
  # PostgreSQL Database
  postgres:
    image: docker.io/library/postgres:16
    container_name: sw-campus-postgres
    environment:
      POSTGRES_DB: swcampus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    # RAM 최적화: PostgreSQL 메모리 제한
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Redis
  redis:
    image: docker.io/library/redis:alpine
    container_name: sw-campus-redis
    ports:
      - "6379:6379"
    # RAM 최적화: Redis 메모리 제한
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

  # OCR AI Service (비활성화 - certificate.ocr.enabled=false)
  # CPU/RAM 사용량 최적화를 위해 비활성화, 재활성화 시 주석 해제
  # ocr:
  #   image: docker.io/zionge2k/sw-campus-ocr:latest
  #   container_name: sw-campus-ocr
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   healthcheck:
  #     test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
  #     interval: 30s
  #     timeout: 10s
  #     start_period: 60s
  #     retries: 3
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #       reservations:
  #         memory: 512M

  # Spring Boot Server (optional - for full stack local dev)
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: sw-campus-server
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=local
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/swcampus
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=postgres
  #     - OCR_SERVICE_URL=http://ocr:8000
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #       reservations:
  #         memory: 512M

volumes:
  postgres_data:
