-- 초기 스키마 생성
-- Flyway 마이그레이션 파일 V1

-- 1. Members 테이블 (사용자)
CREATE TABLE IF NOT EXISTS members (
    user_id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    nickname VARCHAR(255),
    phone VARCHAR(255),
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    org_id BIGINT,
    location VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_members_email ON members(email);
CREATE INDEX IF NOT EXISTS idx_members_org_id ON members(org_id);

-- 2. Organizations 테이블 (기관)
CREATE TABLE IF NOT EXISTS organizations (
    org_id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    org_name VARCHAR(255),
    description TEXT,
    approval_status INTEGER,
    certificate_url TEXT,
    gov_auth VARCHAR(100),
    facility_image_url TEXT,
    facility_image_url2 TEXT,
    facility_image_url3 TEXT,
    facility_image_url4 TEXT,
    org_logo_url TEXT,
    homepage TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_organizations_user FOREIGN KEY (user_id) REFERENCES members(user_id)
);

CREATE INDEX IF NOT EXISTS idx_organizations_user_id ON organizations(user_id);

-- 3. Categories 테이블 (카테고리)
CREATE TABLE IF NOT EXISTS CATEGORIES (
    CATEGORY_ID BIGSERIAL PRIMARY KEY,
    PID BIGINT,
    CATEGORY_NAME VARCHAR(255) NOT NULL,
    SORT INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_categories_pid ON CATEGORIES(PID);

-- 4. Curriculums 테이블 (커리큘럼)
CREATE TABLE IF NOT EXISTS CURRICULUMS (
    CURRICULUM_ID BIGSERIAL PRIMARY KEY,
    CATEGORY_ID BIGINT NOT NULL,
    CURRICULUM_NAME VARCHAR(255),
    CONSTRAINT fk_curriculums_category FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

CREATE INDEX IF NOT EXISTS idx_curriculums_category_id ON CURRICULUMS(CATEGORY_ID);

-- 5. Teachers 테이블 (강사)
CREATE TABLE IF NOT EXISTS TEACHERS (
    TEACHER_ID BIGSERIAL PRIMARY KEY,
    TEACHER_NAME VARCHAR(50) NOT NULL,
    TEACHER_DESCRIPTION TEXT,
    TEACHER_IMAGE_URL TEXT
);

-- 6. Lectures 테이블 (강의)
CREATE TABLE IF NOT EXISTS LECTURES (
    LECTURE_ID BIGSERIAL PRIMARY KEY,
    ORG_ID BIGINT NOT NULL,
    LECTURE_NAME VARCHAR(255) NOT NULL,
    DAYS VARCHAR(255),
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL,
    LECTURE_LOC VARCHAR(50) NOT NULL,
    LOCATION VARCHAR(255),
    RECRUIT_TYPE VARCHAR(50) NOT NULL,
    SUBSIDY DECIMAL(19,2) NOT NULL,
    LECTURE_FEE DECIMAL(19,2) NOT NULL,
    EDU_SUBSIDY DECIMAL(19,2) NOT NULL,
    GOAL TEXT,
    MAX_CAPACITY INTEGER,
    EQUIP_PC VARCHAR(50),
    EQUIP_MERIT TEXT,
    BOOKS BOOLEAN NOT NULL DEFAULT FALSE,
    RESUME BOOLEAN NOT NULL DEFAULT FALSE,
    MOCK_INTERVIEW BOOLEAN NOT NULL DEFAULT FALSE,
    EMPLOYMENT_HELP BOOLEAN NOT NULL DEFAULT FALSE,
    AFTER_COMPLETION BOOLEAN,
    URL TEXT,
    LECTURE_IMAGE_URL TEXT,
    STATUS VARCHAR(50) NOT NULL,
    LECTURE_AUTH_STATUS BOOLEAN,
    PROJECT_NUM INTEGER,
    PROJECT_TIME INTEGER,
    PROJECT_TEAM VARCHAR(255),
    PROJECT_TOOL VARCHAR(255),
    PROJECT_MENTOR BOOLEAN,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    DEADLINE TIMESTAMP,
    TOTAL_DAYS INTEGER NOT NULL,
    TOTAL_TIMES INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lectures_org FOREIGN KEY (ORG_ID) REFERENCES organizations(org_id)
);

CREATE INDEX IF NOT EXISTS idx_lectures_org_id ON LECTURES(ORG_ID);
CREATE INDEX IF NOT EXISTS idx_lectures_status ON LECTURES(STATUS);

-- 7. Lecture Steps 테이블 (강의 선발절차)
CREATE TABLE IF NOT EXISTS LECTURE_STEPS (
    STEP_ID BIGSERIAL PRIMARY KEY,
    LECTURE_ID BIGINT NOT NULL,
    STEP_TYPE VARCHAR(50) NOT NULL,
    STEP_ORDER INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lecture_steps_lecture FOREIGN KEY (LECTURE_ID) REFERENCES LECTURES(LECTURE_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_lecture_steps_lecture_id ON LECTURE_STEPS(LECTURE_ID);

-- 8. Lecture Adds 테이블 (강의 추가혜택)
CREATE TABLE IF NOT EXISTS LECTURE_ADDS (
    ADD_ID BIGSERIAL PRIMARY KEY,
    LECTURE_ID BIGINT NOT NULL,
    ADD_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT fk_lecture_adds_lecture FOREIGN KEY (LECTURE_ID) REFERENCES LECTURES(LECTURE_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_lecture_adds_lecture_id ON LECTURE_ADDS(LECTURE_ID);

-- 9. Lecture Quals 테이블 (강의 지원자격)
CREATE TABLE IF NOT EXISTS LECTURE_QUALS (
    QUAL_ID BIGSERIAL PRIMARY KEY,
    LECTURE_ID BIGINT NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    TEXT TEXT NOT NULL,
    CONSTRAINT fk_lecture_quals_lecture FOREIGN KEY (LECTURE_ID) REFERENCES LECTURES(LECTURE_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_lecture_quals_lecture_id ON LECTURE_QUALS(LECTURE_ID);

-- 10. Lecture Curriculums 테이블 (강의-커리큘럼 매핑)
CREATE TABLE IF NOT EXISTS LECTURE_CURRICULUMS (
    id BIGSERIAL PRIMARY KEY,
    LECTURE_ID BIGINT NOT NULL,
    CURRICULUM_ID BIGINT NOT NULL,
    LEVEL VARCHAR(50),
    CONSTRAINT fk_lecture_curriculums_lecture FOREIGN KEY (LECTURE_ID) REFERENCES LECTURES(LECTURE_ID) ON DELETE CASCADE,
    CONSTRAINT fk_lecture_curriculums_curriculum FOREIGN KEY (CURRICULUM_ID) REFERENCES CURRICULUMS(CURRICULUM_ID),
    CONSTRAINT uk_lecture_curriculum UNIQUE (LECTURE_ID, CURRICULUM_ID)
);

CREATE INDEX IF NOT EXISTS idx_lecture_curriculums_lecture_id ON LECTURE_CURRICULUMS(LECTURE_ID);
CREATE INDEX IF NOT EXISTS idx_lecture_curriculums_curriculum_id ON LECTURE_CURRICULUMS(CURRICULUM_ID);

-- 11. Lecture Teachers 테이블 (강의-강사 매핑)
CREATE TABLE IF NOT EXISTS LECTURE_TEACHERS (
    id BIGSERIAL PRIMARY KEY,
    LECTURE_ID BIGINT NOT NULL,
    TEACHER_ID BIGINT NOT NULL,
    CONSTRAINT fk_lecture_teachers_lecture FOREIGN KEY (LECTURE_ID) REFERENCES LECTURES(LECTURE_ID) ON DELETE CASCADE,
    CONSTRAINT fk_lecture_teachers_teacher FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS(TEACHER_ID),
    CONSTRAINT uk_lecture_teacher UNIQUE (LECTURE_ID, TEACHER_ID)
);

CREATE INDEX IF NOT EXISTS idx_lecture_teachers_lecture_id ON LECTURE_TEACHERS(LECTURE_ID);
CREATE INDEX IF NOT EXISTS idx_lecture_teachers_teacher_id ON LECTURE_TEACHERS(TEACHER_ID);

-- 12. Social Accounts 테이블 (소셜 계정)
CREATE TABLE IF NOT EXISTS social_accounts (
    id BIGSERIAL PRIMARY KEY,
    member_id BIGINT NOT NULL,
    provider VARCHAR(50) NOT NULL,
    provider_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_social_accounts_member FOREIGN KEY (member_id) REFERENCES members(user_id) ON DELETE CASCADE,
    CONSTRAINT uk_social_accounts_provider UNIQUE (provider, provider_id)
);

CREATE INDEX IF NOT EXISTS idx_social_accounts_member_id ON social_accounts(member_id);

-- 13. Refresh Tokens 테이블 (리프레시 토큰)
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    token VARCHAR(500) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES members(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);

-- 14. Email Verifications 테이블 (이메일 인증)
CREATE TABLE IF NOT EXISTS email_verifications (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_email_verifications_email ON email_verifications(email);
CREATE INDEX IF NOT EXISTS idx_email_verifications_token ON email_verifications(token);

-- 15. Certificates 테이블 (수료증)
CREATE TABLE IF NOT EXISTS certificates (
    certificate_id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    lecture_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    image_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_certificates_user FOREIGN KEY (user_id) REFERENCES members(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_certificates_lecture FOREIGN KEY (lecture_id) REFERENCES LECTURES(LECTURE_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_certificates_user_id ON certificates(user_id);
CREATE INDEX IF NOT EXISTS idx_certificates_lecture_id ON certificates(lecture_id);

-- 16. Reviews 테이블 (리뷰)
CREATE TABLE IF NOT EXISTS reviews (
    review_id BIGSERIAL PRIMARY KEY,
    lecture_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    comment TEXT,
    score DECIMAL(2,1),
    blurred BOOLEAN DEFAULT FALSE,
    review_status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reviews_lecture FOREIGN KEY (lecture_id) REFERENCES LECTURES(LECTURE_ID) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES members(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_reviews_lecture_id ON reviews(lecture_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON reviews(user_id);

-- 17. Reviews Details 테이블 (리뷰 상세)
CREATE TABLE IF NOT EXISTS reviews_details (
    review_detail_id BIGSERIAL PRIMARY KEY,
    review_id BIGINT NOT NULL,
    category VARCHAR(50),
    score DECIMAL(2,1),
    detail_comment TEXT,
    CONSTRAINT fk_reviews_details_review FOREIGN KEY (review_id) REFERENCES reviews(review_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_reviews_details_review_id ON reviews_details(review_id);

-- 18. Carts 테이블 (장바구니)
CREATE TABLE IF NOT EXISTS carts (
    cart_id BIGSERIAL PRIMARY KEY,
    lecture_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carts_lecture FOREIGN KEY (lecture_id) REFERENCES LECTURES(LECTURE_ID) ON DELETE CASCADE,
    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES members(user_id) ON DELETE CASCADE,
    CONSTRAINT uk_cart_lecture_user UNIQUE (lecture_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_carts_lecture_id ON carts(lecture_id);
CREATE INDEX IF NOT EXISTS idx_carts_user_id ON carts(user_id);

-- 19. Informations 테이블 (사용자 정보)
CREATE TABLE IF NOT EXISTS informations (
    user_id BIGINT PRIMARY KEY,
    major VARCHAR(100),
    bootcamp BOOLEAN,
    wanted_job VARCHAR(100),
    license VARCHAR(100),
    gov_card BOOLEAN,
    affordable DECIMAL(19,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_informations_user FOREIGN KEY (user_id) REFERENCES members(user_id) ON DELETE CASCADE
);

