-- Auto-generated migration file: V4__seed_organizations.sql
-- Generated at: 2025-12-18 20:20:35

INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (1, '(사)한국기술사업화진흥협회 대구평생교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (2, '(사)한국능률협회', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (3, '(사)한국무역협회무역아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (4, '(재)대덕인재개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (5, '(재)한국직업능력교육원(구.열린직업전문학교)', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (6, '(주)KD아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (7, '(주)KD아카데미컴퓨터학원 구리남양주점', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (8, '(주)KD아카데미컴퓨터학원 하남미사점', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (9, '(주)LG CNS Learning&Development담당(I)', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (10, '(주)그렙', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (11, '(주)글로벌아카데미(구.글로벌직업전문학교)', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (12, '(주)누리마루학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (13, '(주)더존비즈온', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (14, '(주)동아일보사', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (15, '(주)모두의연구소', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (16, '(주)문화방송', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (17, '(주)셀트리온', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (18, '(주)솔데스크', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (19, '(주)신세계아이앤씨', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (20, '(주)알파코', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (21, '(주)에스비에스에이앤티', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (22, '(주)에스엠유니버스', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (23, '(주)엘리스그룹', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (24, '(주)엠비씨플러스', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (25, '(주)엠아이티능력개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (26, '(주)예담직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (27, '(주)우리인재개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (28, '(주)우아한형제들', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (29, '(주)웅진씽크빅', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (30, '(주)원주문화방송', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (31, '(주)이스트소프트', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (32, '(주)이젠컴퓨터아카데미안산', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (33, '(주)천재교육', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (34, '(주)케이티클라우드', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (35, '(주)포스코 미래창조아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (36, '(주)한국능률협회컨설팅', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (37, '(주)한국디지털직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (38, '(주)휴먼교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (39, '(학교법인)인하대학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (40, '4세대아카데미컴퓨터학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (41, 'DW아카데미학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (42, 'KD아카데미컴퓨터학원 김포점', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (43, 'KH인재교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (44, 'KH정보교육원 강남지원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (45, 'KH정보교육원 부산지원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (46, 'KH정보교육원 종로지원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (47, 'The국제직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (48, '강남 그린컴퓨터아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (49, '강원대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (50, '건국대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (51, '경북대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (52, '경북산업직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (53, '경영기술개발원교육센터주식회사', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (54, '고양산업진흥원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (55, '광운대학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (56, '광주 데이터사이언스 아카데미(SES)', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (57, '광주IT(아이티)학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (58, '광주과학기술원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (59, '구디아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (60, '구트아카데미학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (61, '국립경국대학교 산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (62, '국립부경대학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (63, '국립순천대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (64, '국제인재개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (65, '국제직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (66, '그린아이티아카데미학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (67, '그린컴퓨터디자인학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (68, '그린컴퓨터아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (69, '그린컴퓨터아카데미 부산', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (70, '그린컴퓨터아카데미 신촌', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (71, '그린컴퓨터아트학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (72, '글로벌산업기술교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (73, '글로벌아이티(IT)인재개발학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (74, '네이버클라우드주식회사', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (75, '넥스트러너스평생교육시설', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (76, '노원그린컴퓨터아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (77, '다산에듀 성남센터(분당이탱크)', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (78, '대구가톨릭대학교 인재개발교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (79, '대구경북첨단의료산업진흥재단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (80, '대신IT평생교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (81, '대우능력개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (82, '대한상공회의소', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (83, '대한상공회의소 경기인력개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (84, '대한상공회의소 서울기술교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (85, '대한상공회의소 충남인력개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (86, '대한상공회의소광주인력개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (87, '대한상공회의소부산인력개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (88, '대한상공회의소인천인력개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (89, '더조은컴퓨터아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (90, '더조은컴퓨터아카데미 종로', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (91, '더조은컴퓨터아카데미학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (92, '더조은컴퓨터아트학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (93, '더조은컴퓨터학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (94, '동성인재개발교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (95, '동아대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (96, '두드림IT교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (97, '두드림컴퓨터아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (98, '두드림컴퓨터학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (99, '라인컴퓨터아트학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (100, '러닝스푼즈학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (101, '렛유인에듀이공계핵심인재양성평생교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (102, '멀티캠퍼스', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (103, '메가HRD센터평생교육시설', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (104, '메가스터디아이티(IT)아카데미학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (105, '메가스터디컴퓨터아카데미신촌학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (106, '메가존클라우드 아이티평생교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (107, '메디치교육센터 평생교육시설', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (108, '명지대학교 산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (109, '모블교육센터평생교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (110, '목포국제직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (111, '미래경영교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (112, '미래융합교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (113, '방송정보국제교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (114, '백석대학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (115, '베스핀글로벌주식회사', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (116, '봄아카데미학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (117, '부산IT교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (118, '부산IT아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (119, '부산기술직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (120, '부산대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (121, '부산더조은직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (122, '부산예일직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (123, '부스트캠프평생교육시설', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (124, '부천그린컴퓨터학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (125, '부천대학 산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (126, '비트컴퓨터비트교육센터평생교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (127, '사단법인 충북바이오산학융합원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (128, '사단법인중소기업기술혁신협회충북지회', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (129, '삼성국민취업아카데미(주)', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (130, '삼성중공업(주)거제조선소', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (131, '삼육대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (132, '삼정회계법인', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (133, '상명대학교천안산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (134, '서울IT아카데미 홍대', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (135, '서울대학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (136, '선문대학교 산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (137, '성결대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (138, '성균관대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (139, '성남 그린컴퓨터아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (140, '세한대학교당진산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (141, '솔데스크강남학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (142, '순천향대학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (143, '스마트인재개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (144, '시사IT아카데미평생교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (145, '쌍용강북교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (146, '쌍용교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (147, '아시아경제 교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (148, '아이티윌', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (149, '아이티윌 부산교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (150, '아주대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (151, '안산 그린컴퓨터아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (152, '안양대학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (153, '애드인에듀 아카데미 구로가산센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (154, '양산직업학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (155, '양정인력개발센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (156, '어소트락평생교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (157, '에듀윌 국비교육원 구로센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (158, '에듀윌 국비교육원 부평센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (159, '에듀윌 국비교육원 성남센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (160, '에이아이아카데미학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (161, '에이치아카데미 D&D교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (162, '에이콘아카데미 홍대학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (163, '에이콘아카데미(강남)', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (164, '에티버스러닝평생교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (165, '엑스퍼트 아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (166, '엠비씨(MBC)아카데미 컴퓨터교육센터 본점', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (167, '엠비씨(MBC)아카데미 컴퓨터교육센터 수원점', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (168, '엠비씨(MBC)아카데미 컴퓨터교육센터 화곡점', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (169, '엠비씨(MBC)아카데미 컴퓨터국비지원교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (170, '엠비씨(MBC)아카데미컴퓨터학원 천호점', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (171, '역삼 그린컴퓨터아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (172, '연세IT미래교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (173, '연세대학교 산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (174, '연희직업전문학교(주)', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (175, '영남기술직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (176, '영남대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (177, '영남인재교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (178, '영진직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (179, '예원예술대학교 산학협력단(양주캠퍼스)', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (180, '오라클자바교육학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (181, '우송대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (182, '유비온디지털교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (183, '유원대학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (184, '윤성컴퓨터디자인DX아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (185, '윤성컴퓨터디자인아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (186, '은곡직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (187, '이젠IT아카데미학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (188, '이젠아카데미 DX교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (189, '이젠아카데미DX교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (190, '이젠아카데미컴퓨터학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (191, '이젠컴퓨터아트서비스학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (192, '인천 그린컴퓨터아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (193, '인천대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (194, '인천더조은컴퓨터아트학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (195, '인천일보아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (196, '인포섹 아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (197, '재능대학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (198, '재단법인 국제인재능력개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (199, '재단법인대구디지털혁신진흥원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (200, '재단법인울산정보산업진흥원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (201, '전남대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (202, '전주문화방송(주)', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (203, '주식회사  하이테커', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (204, '주식회사 로켓부스트', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (205, '주식회사경일게임아이티아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (206, '주식회사구름', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (207, '주식회사멋쟁이사자처럼', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (208, '주식회사원티드랩', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (209, '주식회사코드스테이츠', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (210, '중부대학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (211, '중앙정보기술인재개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (212, '중앙정보처리학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (213, '중앙직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (214, '청주대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (215, '케이비에스미디어주식회사', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (216, '케이아이씨캠퍼스학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (217, '케이지에듀원 아이티뱅크종로학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (218, '케이지에듀원아이티뱅크강남학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (219, '케이지에듀원아이티뱅크노량진학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (220, '코드랩아카데미학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (221, '코드잇 평생교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (222, '코리아IT아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (223, '코리아아이티(IT)아카데미학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (224, '투썬캠퍼스 분당센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (225, '팀스파르타주식회사', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (226, '패스트캠퍼스강남학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (227, '플레이데이터평생교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (228, '하이미디어IT인재개발학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (229, '하이미디어아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (230, '하이미디어아카데미인재개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (231, '하이미디어컴퓨터디자인학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (232, '하이미디어컴퓨터학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (233, '한가람IT전문교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (234, '한경닷컴IT교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (235, '한경아카데미', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (236, '한국ICT인재개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (237, '한국IT교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (238, '한국경영인증원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (239, '한국공학대학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (240, '한국기술교육대학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (241, '한국기술교육직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (242, '한국능력개발직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (243, '한국생산성본부', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (244, '한국소프트웨어교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (245, '한국소프트웨어인재개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (246, '한국스마트정보교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (247, '한국아이티전문학원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (248, '한국인공지능·소프트웨어산업협회', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (249, '한국전파진흥협회', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (250, '한국정보교육원(구.경원직업전문학교)', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (251, '한국지능형교통체계협회', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (252, '한국직업능력교육원 안산', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (253, '한국직업능력교육원(구.열린드림기술교육원)', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (254, '한국직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (255, '한국직업전문학교 1캠퍼스', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (256, '한국표준협회', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (257, '한국품질재단 평생교육시설', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (258, '한국품질재단대구평생교육원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (259, '한국휴렛팩커드(유)교육센터', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (260, '한남대학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (261, '한성대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (262, '한양대학교에리카산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (263, '한울직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (264, '한컴아카데미(분당)', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (265, '현대경제연구원 인재개발원', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (266, '호서대학교산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (267, '홍익대학교세종캠퍼스산학협력단', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (268, '효성직업전문학교', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (269, '휴먼IT교육센터_국비지원무료교육', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (270, '휴먼IT교육센터_내일배움카드교육', 1, 'APPROVED', NOW(), NOW()) ON CONFLICT DO NOTHING;
SELECT setval('swcampus.organizations_org_id_seq', (SELECT COALESCE(MAX(org_id), 1) FROM swcampus.organizations));
