-- Auto-generated migration file: V4__seed_organizations.sql
-- Generated at: 2025-12-17 10:28:23

INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (1, '(사)한국능률협회', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (2, '(재)대덕인재개발원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (3, '(주)KD아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (4, '(주)KD아카데미컴퓨터학원 하남미사점', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (5, '(주)LG CNS Learning&Development담당(I)', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (6, '(주)그렙', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (7, '(주)글로벌아카데미(구.글로벌직업전문학교)', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (8, '(주)모두의연구소', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (9, '(주)문화방송', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (10, '(주)솔데스크', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (11, '(주)알파코', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (12, '(주)에스엠유니버스', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (13, '(주)엘리스그룹', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (14, '(주)예담직업전문학교', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (15, '(주)우리인재개발원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (16, '(주)원주문화방송', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (17, '(주)이스트소프트', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (18, '(주)이젠컴퓨터아카데미안산', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (19, '(주)천재교육', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (20, '(주)케이티클라우드', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (21, '(주)한국능률협회컨설팅', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (22, '(주)휴먼교육센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (23, '4세대아카데미컴퓨터학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (24, 'DW아카데미학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (25, 'KD아카데미컴퓨터학원 김포점', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (26, 'KH정보교육원 부산지원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (27, 'KH정보교육원 종로지원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (28, 'The국제직업전문학교', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (29, '경북대학교산학협력단', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (30, '경북산업직업전문학교', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (31, '경영기술개발원교육센터주식회사', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (32, '구디아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (33, '국립부경대학교', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (34, '국제인재개발원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (35, '그린컴퓨터아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (36, '그린컴퓨터아카데미 부산', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (37, '그린컴퓨터아카데미 신촌', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (38, '그린컴퓨터아트학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (39, '글로벌산업기술교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (40, '글로벌아이티(IT)인재개발학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (41, '넥스트러너스평생교육시설', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (42, '노원그린컴퓨터아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (43, '대신IT평생교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (44, '대우능력개발원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (45, '대한상공회의소', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (46, '대한상공회의소 경기인력개발원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (47, '대한상공회의소 서울기술교육센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (48, '대한상공회의소부산인력개발원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (49, '대한상공회의소인천인력개발원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (50, '더조은컴퓨터아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (51, '더조은컴퓨터아카데미 종로', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (52, '더조은컴퓨터아트학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (53, '더조은컴퓨터학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (54, '동성인재개발교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (55, '두드림IT교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (56, '두드림컴퓨터아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (57, '두드림컴퓨터학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (58, '렛유인에듀이공계핵심인재양성평생교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (59, '멀티캠퍼스', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (60, '메가HRD센터평생교육시설', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (61, '메가스터디아이티(IT)아카데미학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (62, '메가존클라우드 아이티평생교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (63, '명지대학교 산학협력단', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (64, '모블교육센터평생교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (65, '목포국제직업전문학교', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (66, '미래경영교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (67, '미래융합교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (68, '백석대학교산학협력단', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (69, '베스핀글로벌주식회사', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (70, '부산IT교육센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (71, '부산IT아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (72, '부산대학교산학협력단', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (73, '부산예일직업전문학교', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (74, '삼성국민취업아카데미(주)', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (75, '삼정회계법인', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (76, '성결대학교산학협력단', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (77, '성균관대학교산학협력단', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (78, '성남 그린컴퓨터아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (79, '솔데스크강남학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (80, '스마트인재개발원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (81, '시사IT아카데미평생교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (82, '쌍용강북교육센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (83, '아시아경제 교육센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (84, '아이티윌', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (85, '아이티윌 부산교육센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (86, '애드인에듀 아카데미 구로가산센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (87, '양정인력개발센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (88, '어소트락평생교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (89, '에듀윌 국비교육원 구로센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (90, '에듀윌 국비교육원 부평센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (91, '에듀윌 국비교육원 성남센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (92, '에이치아카데미 D&D교육센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (93, '에이콘아카데미 홍대학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (94, '엠비씨(MBC)아카데미 컴퓨터교육센터 본점', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (95, '엠비씨(MBC)아카데미 컴퓨터교육센터 수원점', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (96, '엠비씨(MBC)아카데미 컴퓨터교육센터 화곡점', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (97, '엠비씨(MBC)아카데미 컴퓨터국비지원교육센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (98, '엠비씨(MBC)아카데미컴퓨터학원 천호점', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (99, '역삼 그린컴퓨터아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (100, '연세IT미래교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (101, '연희직업전문학교(주)', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (102, '영남인재교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (103, '오라클자바교육학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (104, '유비온디지털교육센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (105, '윤성컴퓨터디자인DX아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (106, '윤성컴퓨터디자인아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (107, '이젠IT아카데미학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (108, '이젠아카데미 DX교육센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (109, '이젠아카데미DX교육센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (110, '이젠아카데미컴퓨터학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (111, '이젠컴퓨터아트서비스학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (112, '인천 그린컴퓨터아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (113, '인천더조은컴퓨터아트학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (114, '재단법인 국제인재능력개발원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (115, '전주문화방송(주)', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (116, '주식회사경일게임아이티아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (117, '주식회사구름', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (118, '주식회사멋쟁이사자처럼', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (119, '주식회사원티드랩', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (120, '중앙HTA IT교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (121, '중앙정보기술인재개발원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (122, '중앙정보처리학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (123, '케이비에스미디어주식회사', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (124, '케이지에듀원 아이티뱅크종로학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (125, '코드랩아카데미학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (126, '코드잇 평생교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (127, '코리아IT아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (128, '팀스파르타주식회사', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (129, '패스트캠퍼스강남학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (130, '플레이데이터평생교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (131, '하이미디어IT인재개발학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (132, '하이미디어아카데미', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (133, '하이미디어아카데미인재개발원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (134, '하이미디어컴퓨터디자인학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (135, '하이미디어컴퓨터학원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (136, '한경닷컴IT교육센터', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (137, '한국ICT인재개발원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (138, '한국IT교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (139, '한국기술교육직업전문학교', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (140, '한국생산성본부', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (141, '한국소프트웨어인재개발원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (142, '한국스마트정보교육원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (143, '한국전파진흥협회', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (144, '한국정보교육원(구.경원직업전문학교)', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (145, '한국지능형교통체계협회', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (146, '한국직업능력교육원 안산', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (147, '한국직업능력교육원(구.열린드림기술교육원)', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (148, '한국직업전문학교', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (149, '한국표준협회', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (150, '한울직업전문학교', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (151, '현대경제연구원 인재개발원', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (152, '휴먼IT교육센터_국비지원무료교육', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO swcampus.organizations (org_id, org_name, user_id, approval_status, created_at, updated_at) VALUES (153, '휴먼IT교육센터_내일배움카드교육', 1, 1, NOW(), NOW()) ON CONFLICT DO NOTHING;
SELECT setval('swcampus.organizations_org_id_seq', (SELECT COALESCE(MAX(org_id), 1) FROM swcampus.organizations));
