-- Auto-generated migration file: V6__seed_curriculums.sql
-- Generated at: 2025-12-17 09:24:27

INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (1, 2, '프로그래밍 언어 핵심 (C++ / C#)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (2, 2, '자료구조 및 알고리즘') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (3, 2, '게임 수학 및 물리학 기초') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (4, 2, 'Windows API 및 시스템 프로그래밍') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (5, 2, '게임 엔진 기초 및 씬(Scene) 구성') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (6, 2, '캐릭터 제어 및 FSM(유한상태머신)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (7, 2, '2D/3D 그래픽스 및 셰이더') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (8, 2, 'UI/UX 시스템 및 사운드 미들웨어') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (9, 2, '네트워크 및 멀티플레이어 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (10, 2, '게임 최적화 및 상용화 프로젝트') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (11, 3, '프로그래밍 언어 핵심 (C++ / C#)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (12, 3, '자료구조 및 알고리즘') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (13, 3, '게임 수학 및 물리학 기초') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (14, 3, 'Windows API 및 시스템 프로그래밍') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (15, 3, '게임 엔진 기초 및 씬(Scene) 구성') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (16, 3, '캐릭터 제어 및 FSM(유한상태머신)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (17, 3, '2D/3D 그래픽스 및 셰이더') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (18, 3, 'UI/UX 시스템 및 사운드 미들웨어') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (19, 3, '네트워크 및 멀티플레이어 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (20, 3, '게임 최적화 및 상용화 프로젝트') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (21, 4, '프로그래밍 언어 핵심 (C++ / C#)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (22, 4, '자료구조 및 알고리즘') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (23, 4, '게임 수학 및 물리학 기초') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (24, 4, 'Windows API 및 시스템 프로그래밍') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (25, 4, '게임 엔진 기초 및 씬(Scene) 구성') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (26, 4, '캐릭터 제어 및 FSM(유한상태머신)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (27, 4, '2D/3D 그래픽스 및 셰이더') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (28, 4, 'UI/UX 시스템 및 사운드 미들웨어') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (29, 4, '네트워크 및 멀티플레이어 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (30, 4, '게임 최적화 및 상용화 프로젝트') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (31, 5, '프로그래밍 언어 핵심 (C++ / C#)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (32, 5, '자료구조 및 알고리즘') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (33, 5, '게임 수학 및 물리학 기초') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (34, 5, 'Windows API 및 시스템 프로그래밍') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (35, 5, '게임 엔진 기초 및 씬(Scene) 구성') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (36, 5, '캐릭터 제어 및 FSM(유한상태머신)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (37, 5, '2D/3D 그래픽스 및 셰이더') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (38, 5, 'UI/UX 시스템 및 사운드 미들웨어') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (39, 5, '네트워크 및 멀티플레이어 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (40, 5, '게임 최적화 및 상용화 프로젝트') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (41, 6, '커리큘럼') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (42, 7, '커리큘럼') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (43, 8, '커리큘럼') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (44, 9, '커리큘럼') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (45, 10, '커리큘럼') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (46, 11, '커리큘럼') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (47, 12, '커리큘럼') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (48, 14, '커리큘럼') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (49, 15, '커리큘럼') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name) VALUES (50, 16, '커리큘럼') ON CONFLICT DO NOTHING;
SELECT setval('swcampus.curriculums_curriculum_id_seq', (SELECT COALESCE(MAX(curriculum_id), 1) FROM swcampus.curriculums));
