-- Auto-generated migration file: V6__seed_curriculums.sql
-- Generated at: 2025-12-18 20:20:35

INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (1, 3, '웹 퍼블리싱', '화면을 구조화하고 스타일링하는 가장 기초 단계') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (2, 3, '자바스크립트 프로그래밍', '프레임워크를 배우기 전, 언어의 논리를 다지는 단계') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (3, 3, '비동기 프로그래밍 & 통신', '데이터를 다루는 개발자의 핵심 역량') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (4, 3, 'TypeScript', '대규모 서비스의 유지보수를 위한 필수 안전장치') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (5, 3, '프론트엔드 프레임워크', '실무에서 가장 많이 쓰는 도구를 배우는 메인 구간') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (6, 3, '상태 관리 & 성능 최적화', '데이터 흐름 제어와 불필요한 렌더링 방지') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (7, 3, '웹 아키텍처 & SSR', '하이브리드 렌더링 및 차세대 웹 애플리케이션 구축') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (8, 3, '백엔드 & 데이터베이스 기초', '프론트엔드 개발자라도 백엔드를 알아야 협업이 가능') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (9, 3, 'CS 지식 & 코딩 테스트', '면접과 코딩 테스트를 통과하기 위한 준비') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (10, 3, '협업 배포 & 실무 프로젝트', '최종 결과물을 만들고 서비스하는 단계') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (11, 4, '프로그래밍 언어 코어', '개발자와 컴퓨터가 대화하는 ''주력 언어''를 마스터') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (12, 4, '웹 서버 & 네트워크 기초', '인터넷이 동작하는 원리') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (13, 4, '백엔드 프레임워크', '실무 개발의 핵심 도구 
Java (Spring)
Node.js (NestJS)
Python (Django/FastAPI)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (14, 4, '데이터베이스 설계', '데이터를 저장하고 관리하는 창고') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (15, 4, '데이터 접근 기술', '자바 코드와 DB를 연결하는 기술') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (16, 4, 'API 개발 & 보안', '외부(프론트엔드)와 소통하는 문을 만듬') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (17, 4, '서버 배포 & 인프라', '내가 만든 서버를 인터넷 세상에 올림') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (18, 4, 'CI/CD & 자동화', '코드 수정부터 배포까지의 과정을 자동화') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (19, 4, '대용량 트래픽 & 성능 최적화', '사람이 몰려도 서버가 터지지 않게 튼튼하게 튜닝') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (20, 4, '협업 배포 & 실무 프로젝트', '최종 결과물을 만들고 서비스하는 단계') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (21, 5, '웹 기초 & UI 구현', '사용자가 보는 화면의 뼈대를 만들고 예쁘게 꾸미는 법을 배움') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (22, 5, '프론트엔드 프레임워크', '화면을 레고 블록처럼 효율적으로 조립하기 위해 리액트등을 배움') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (23, 5, '백엔드 언어 & 서버', '데이터 처리를 담당할 ''두뇌''를 만듬') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (24, 5, '데이터베이스 & 모델링', '회원 정보나 상품 데이터를 저장할 ''창고''를 짓고 정리하는 법을 배움') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (25, 5, 'API 설계 및 통신', '화면(프론트)이 서버(백엔드)와의 대화 방법을 배움') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (26, 5, '인증 & 보안', '아무나 들어오지 못하게 문을 잠그고, 회원가입/로그인 기능을 만듬') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (27, 5, '상태 관리 및 데이터 캐싱', '사용자가 보는 화면과 데이터를 빠르게 일치시키는 기술') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (28, 5, '배포 & 데브옵스', '내가 만든 서비스를 클라우드 에 올려서 사람들이 접속할 수 있게 만듬') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (29, 5, '심화 아키텍처', '더 빠르고, 검색엔진에 잘 걸리는 ''프로 수준''의 웹사이트로 업그레이드') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (30, 5, '협업 배포 & 실무 프로젝트', '최종 결과물을 만들고 서비스하는 단계') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (31, 7, '프로그래밍 언어 기초', '앱을 만들기 위한 언어를 배움 (Swift/Kotlin)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (32, 7, 'UI/UX 레이아웃', '스마트폰 화면에 버튼과 그림을 예쁘게 배치') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (33, 7, '화면 이동 & 내비게이션', '홈 화면에서 설정 화면으로 자연스럽게 이동하는 길을 만듬') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (34, 7, '상태 관리 & 데이터 바인딩', '화면의 숫자와 실제 데이터를 실시간으로 일치시킴') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (35, 7, '서버 통신 & API', '앱 혼자 작동하는 게 아니라 인터넷 세상과 대화함') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (36, 7, '로컬 데이터 저장', '인터넷이 없어도 볼 수 있게 데이터를 폰에 저장') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (37, 7, '하드웨어 기능 제어', '스마트폰의 카메라/마이크/위치를 사용') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (38, 7, '앱 배포 & 스토어 등록', '구글 플레이스토어나 애플 앱스토어에 올려서 남들이 다운로드할 수 있게 만듬') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (39, 7, '유지보수 & 테스트', '기능 추가가 쉽고 버그가 없는 튼튼한 앱을 만듬') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (40, 7, '실무 프로젝트', '최종 결과물을 만들고 서비스하는 단계') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (41, 9, '데이터 문해력 및 스프레드시트 활용', '엑셀의 고급 기능을 활용해 데이터를 1차적으로 가공하고 구조를 해석') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (42, 9, '데이터 분석 프로그래밍', 'Python과 핵심 라이브러리를 활용해 대용량 데이터를 효율적으로 처리') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (43, 9, '데이터 추출 및 관리', '기업의 데이터베이스 환경을 이해하고 SQL로 필요한 데이터를 정확히 추출') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (44, 9, '데이터 수집 및 자동화', '웹 크롤링과 API 연동을 통해 분석에 필요한 외부 데이터셋을 직접 구축') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (45, 9, '탐색적 데이터 분석 및 전처리', '데이터의 결측치와 이상치를 정제하고 분포 패턴을 파악하여 품질을 높임') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (46, 9, '통계 분석 및 가설 검증', '통계적 가설 검정을 통한 데이터 패턴 검증 및 객관적 근거 마련') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (47, 9, '예측 모델링 기초', '머신러닝 알고리즘 적용 및 과거 데이터 기반의 미래 수치 예측') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (48, 9, '데이터 시각화 및 대시보드', '전문 도구를 활용한 이해관계자용 인터랙티브 대시보드 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (49, 9, '비즈니스 지표 분석', '서비스 성장을 측정하는 핵심 지표(KPI) 정의 및 현황 진단') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (50, 9, '실무 프로젝트', '최종 결과물을 만들고 서비스하는 단계') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (51, 10, '프로그래밍 & 리눅스', '데이터라는 자재를 다루는 가장 기본적인 도구') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (52, 10, '데이터베이스 & SQL', '데이터 저장소에서 원하는 자료를 정확하고 빠르게 꺼내는 법을 배움') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (53, 10, '데이터 웨어하우스', '여기저기 흩어진 데이터를 분석하기 좋게 한곳에 모아두는 기술') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (54, 10, '대용량 분산 처리', '컴퓨터 한 대로 처리 못 하는 엄청난 양의 데이터를 컴퓨터 여러대가 나눠서 계산하게 시키는 팀플레이 기술') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (55, 10, '워크플로우 자동화', '매일 데이터를 가져와서 정리하라고 자동화 함') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (56, 10, '실시간 데이터 처리', '1초에 수천 건씩 쏟아지는 데이터를 막힘없이 처리') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (57, 10, '클라우드 인프라', '클라우드를 빌려서 거대한 데이터 센터를 구축') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (58, 10, '컨테이너 & 배포', '내 코드가 어떤 컴퓨터에서든 똑같이 실행되도록 표준 규격 컨테이너에 포장해서 배포') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (59, 10, '데이터 품질 & 테스트', '데이터에 구멍이 있거나 이상한 값이 섞여 있지 않은지 감시하는 품질 관리원 역할') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (60, 10, '실무 프로젝트', '최종 결과물을 만들고 서비스하는 단계') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (61, 11, 'Python 프로그래밍 및 AI 수학', 'Python 고급 문법 숙지 및 선형대수·확률통계 등 AI 필수 수학 이론 이해') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (62, 11, '데이터 전처리 및 핸들링', 'Pandas·NumPy를 활용한 비정형 데이터(텍스트·이미지) 정제 및 가공') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (63, 11, '머신러닝/딥러닝 프레임워크 기초', 'PyTorch 또는 TensorFlow를 활용한 인공신경망(ANN) 설계 및 모델링 기초') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (64, 11, '데이터베이스 및 SQL 활용', 'AI 모델 학습용 데이터 구축을 위한 RDBMS 및 SQL 데이터 추출 능력 함양') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (65, 11, '컴퓨터 비전(CV) 및 이미지 처리', 'CNN 아키텍처 기반의 이미지 분류, 객체 탐지(Object Detection) 모델 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (66, 11, '자연어 처리(NLP) 및 LLM 활용', 'Transformer 구조 이해 및 BERT·GPT 등 거대언어모델(LLM) 응용 실습') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (67, 11, '생성형 AI 및 RAG 아키텍처', '벡터 데이터베이스(Vector DB)와 RAG(검색 증강 생성) 기술을 활용한 AI 서비스 구축') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (68, 11, '모델 성능 최적화 및 경량화', '모델 성능 고도화를 위한 파인튜닝(Fine-tuning) 및 모바일/엣지 환경용 경량화 기술 적용') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (69, 11, 'AI 모델 서빙 및 API 개발', 'FastAPI·Flask를 활용한 모델 API 서버 구축 및 실시간 추론 서비스 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (70, 11, 'MLOps 파이프라인 및 클라우드 배포', 'Docker·Kubernetes 기반의 모델 배포 자동화(CI/CD) 및 모니터링 환경 구축') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (71, 11, '실무 프로젝트', '최종 결과물을 만들고 서비스하는 단계') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (72, 13, '리눅스 시스템 관리 및 쉘 스크립팅', '리눅스(Linux) OS 구조 이해 및 쉘 스크립트를 활용한 서버 운영 자동화') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (73, 13, '네트워크 핵심 이론 및 가상화 기초', 'TCP/IP 프로토콜, 서브넷팅 등 네트워크 이론 숙지 및 가상화 기술 이해') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (74, 13, '퍼블릭 클라우드 인프라 구축', '가상 서버(EC2), 네트워크(VPC), 스토리지 등 클라우드 핵심 리소스 생성 및 관리') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (75, 13, '고가용성(HA) 아키텍처 및 로드밸런싱', '트래픽 분산을 위한 로드밸런서(ELB) 구성 및 오토스케일링(Auto Scaling) 아키텍처 설계') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (76, 13, '도커(Docker) 컨테이너 가상화 활용', '애플리케이션의 격리 및 배포 효율화를 위한 도커 이미지 생성 및 컨테이너 운영') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (77, 13, '쿠버네티스(Kubernetes) 클러스터 운영', '대규모 컨테이너 관리를 위한 쿠버네티스 아키텍처 이해 및 파드(Pod)·서비스 배포') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (78, 13, '클라우드 데이터베이스 및 스토리지 관리', 'RDBMS(RDS) 및 NoSQL(DynamoDB) 등 관리형 데이터베이스 서비스 구축 및 운영') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (79, 13, 'IaC 기반 인프라 자동화', '(Terraform/Ansible) 코드로 인프라를 관리하는 IaC 도구 활용 및 프로비저닝 자동화') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (80, 13, 'CI/CD 파이프라인 구축 및 배포', 'Jenkins, GitHub Actions 등을 활용한 지속적 통합·배포(CI/CD) 자동화 시스템 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (81, 13, '실무 프로젝트', '보안 그룹, IAM 등 클라우드 보안 정책 수립 및 엔터프라이즈급 인프라 설계 프로젝트 수행') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (82, 15, '시스템 및 네트워크 핵심 이론', '운영체제(Linux/Windows) 구조 이해 및 TCP/IP 프로토콜 심층 분석') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (83, 15, '보안 프로그래밍 및 스크립팅', 'Python 및 C언어를 활용한 보안 도구 개발 및 자동화 스크립트 작성') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (84, 15, '네트워크 보안 및 트래픽 분석', 'Wireshark를 활용한 패킷 분석 및 스니핑·스푸핑 등 공격 기법 탐지') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (85, 15, '정보보호 개론 및 암호학 기초', '정보보호의 3요소(CIA) 이해 및 대칭키·공개키 등 핵심 암호 알고리즘 학습') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (86, 15, '웹 애플리케이션 보안', 'OWASP Top 10 취약점 분석 및 Burp Suite를 활용한 웹 모의해킹 실습') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (87, 15, '시스템 보안 및 리버스 엔지니어링', '시스템 버퍼 오버플로우 공격 원리 이해 및 리버스 엔지니어링 기초') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (88, 15, '악성코드 분석 및 탐지', '주요 악성코드의 동작 원리 분석 및 샌드박스를 활용한 동적/정적 분석') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (89, 15, '보안 관제 및 로그 분석', '통합 보안 관제 시스템 구축 및 침입 탐지 시스템(IDS/IPS) 로그 분석') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (90, 15, '디지털 포렌식 및 침해 사고 대응', '해킹 사고 발생 시 증거 수집·복구 기술 및 침해 사고 대응 절차 수행') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (91, 15, '실무 프로젝트 및 컨설팅', '기업 인프라 대상 모의해킹 수행 또는 보안 관제 시스템 구축 및 결과 보고서 작성') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (92, 17, 'C/C++ 프로그래밍 및 임베디드 코딩', '메모리 구조 이해 및 포인터를 활용한 효율적인 임베디드 C 프로그래밍') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (93, 17, '마이크로컨트롤러 구조 및 주변장치 제어', 'ARM/AVR 아키텍처 이해 및 GPIO·UART·I2C·SPI 등 핵심 통신 인터페이스 제어') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (94, 17, '센서/액추에이터 제어 및 회로도 분석', '데이터시트 분석을 통한 각종 센서 데이터 수집 및 모터·디스플레이 구동') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (95, 17, '실시간 운영체제(RTOS) 활용', 'FreeRTOS 등을 활용한 멀티태스킹 스케줄링 및 실시간 시스템 제어 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (96, 17, '임베디드 리눅스 시스템 포팅', '타겟 보드(라즈베리파이/Jetson 등)에 부트로더, 커널, 파일시스템 구축 및 포팅') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (97, 17, '리눅스 시스템 프로그래밍', '리눅스 환경에서의 파일 입출력, 프로세스 관리 및 멀티스레드 프로그래밍') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (98, 17, '리눅스 커널 및 디바이스 드라이버 개발', '커널 모듈 프로그래밍 및 하드웨어 제어를 위한 디바이스 드라이버 작성') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (99, 17, 'IoT 무선 통신 및 네트워크 프로그래밍', 'Wi-Fi·Bluetooth·Zigbee 통신 이해 및 소켓 프로그래밍을 통한 네트워크 구축') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (100, 17, 'IoT 클라우드 플랫폼 연동 및 엣지 컴퓨팅', 'MQTT 프로토콜을 활용한 AWS IoT/Azure 연동 및 엣지단의 데이터 처리') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (101, 17, '스마트 IoT 디바이스 제작 융합 프로젝트', 'HW 설계부터 펌웨어, 서버 연동까지 수행하는 스마트 디바이스 상용화 레벨 제작') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (102, 18, '로봇 프로그래밍 언어 (C++ / Python)', '객체지향 C++ 및 Python 프로그래밍 숙지, 로봇 제어를 위한 효율적인 메모리 관리') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (103, 18, '리눅스(Linux) 시스템 및 개발 환경', 'Ubuntu 환경에서의 리눅스 명령어 숙지 및 로봇 개발을 위한 Shell Scripting 활용') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (104, 18, '임베디드 제어 및 센서 인터페이스', 'MCU(STM32/Arduino)를 활용한 모터 제어(PWM) 및 IMU·LiDAR 등 센서 데이터 통신') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (105, 18, '로봇 수학 및 기구학(Kinematics)', '로봇 팔/이동 로봇 해석을 위한 선형대수(행렬) 및 좌표 변환, 정/역기구학 이론 학습') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (106, 18, 'ROS 2 아키텍처 및 통신', '최신 ROS 2(Robot Operating System) 구조 이해 및 노드 간 통신(Topic, Service, Action) 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (107, 18, '로봇 시뮬레이션', 'URDF/Xacro를 활용한 가상 로봇 모델링 및 물리 엔진 기반의 3D 시뮬레이션 환경 구축') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (108, 18, 'SLAM 및 내비게이션', 'LiDAR/Camera 센서 기반의 지도 작성(SLAM) 및 장애물 회피를 포함한 자율주행 경로 계획') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (109, 18, '로봇 비전 및 인식', 'OpenCV 및 딥러닝을 활용한 물체 인식, 거리 추정 및 로봇의 주변 환경 인지 기술') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (110, 18, '매니퓰레이션 및 모션 플래닝', '다관절 로봇 팔 제어를 위한 MoveIt 프레임워크 활용 및 역기구학 기반 모션 제어') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (111, 18, '자율주행/서비스 로봇 융합 프로젝트', '자율주행 배송 로봇 또는 협동 로봇(Cobot)을 활용한 실제 서비스 시나리오 구현 및 검증') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (112, 20, '프로그래밍 언어 핵심 (C++ / C#)', 'C++(언리얼) 또는 C#(유니티)의 문법 숙지 및 객체지향 프로그래밍(OOP) 심화 원리 이해') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (113, 20, '자료구조 및 알고리즘', '게임 성능 최적화를 위한 핵심 자료구조(List, Map 등) 및 길 찾기 알고리즘 활용') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (114, 20, '게임 수학 및 물리학 기초', '3D 공간 구현을 위한 벡터·행렬 등 선형대수 이해 및 물리 엔진(충돌·중력) 원리 학습') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (115, 20, 'Windows API 및 시스템 프로그래밍', '운영체제 구조 이해 및 다이렉트X(DirectX) 기초를 통한 그래픽스 렌더링 파이프라인 학습') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (116, 20, '게임 엔진 기초 및 씬(Scene) 구성', 'Unity 또는 Unreal 엔진 인터페이스 숙지 및 레벨 디자인·오브젝트 배치 실습') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (117, 20, '캐릭터 제어 및 FSM(유한상태머신)', '사용자 입력에 따른 캐릭터 애니메이션 제어 및 NPC 인공지능(AI) 상태 패턴 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (118, 20, '2D/3D 그래픽스 및 셰이더', '3D 모델, 텍스처, 라이팅에 대한 이해 및 셰이더 프로그래밍을 통한 시각 효과 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (119, 20, 'UI/UX 시스템 및 사운드 미들웨어', '사용자 인터페이스(UGUI/UMG) 설계 및 효과적인 사운드 리소스 관리·연동') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (120, 20, '네트워크 및 멀티플레이어 구현', 'TCP/UDP 소켓 프로그래밍 이해 및 멀티플레이어 위치 동기화·데이터 패킷 처리') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (121, 20, '게임 최적화 및 상용화 프로젝트', '프로파일링 툴을 활용한 메모리·프레임 최적화 및 마켓(Steam/PlayStore) 빌드·배포') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (122, 21, '블록체인 핵심 이론 및 암호학', '해시 함수, 공개키 암호화(ECC) 등 암호학 기초 및 블록체인의 무결성 원리 이해') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (123, 21, '합의 알고리즘 및 네트워크 구조', 'PoW(작업증명), PoS(지분증명) 등 합의 메커니즘 이해 및 P2P 네트워크 구조 분석') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (124, 21, '이더리움 가상머신(EVM) 및 트랜잭션', 'EVM의 동작 원리, 가스(Gas) 비용 산정 방식, 트랜잭션 수명 주기에 대한 심층 이해') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (125, 21, '지갑 구조 및 노드 운영', '메타마스크 등 지갑의 HD(계층 결정적) 구조 이해 및 Geth 등을 활용한 로컬 노드 구축') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (126, 21, 'Solidity 프로그래밍 기초 및 심화', 'Solidity 문법 숙지 및 상속, 라이브러리, 메모리 관리 등 효율적인 컨트랙트 작성') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (127, 21, '토큰 표준(ERC) 및 탈중앙화 로직', 'ERC-20(토큰), ERC-721(NFT) 등 핵심 표준 구현 및 투표(DAO), 스테이킹 로직 설계') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (128, 21, '컨트랙트 보안 및 테스트', 'Reentrancy 등 주요 해킹 기법 방어 및 Hardhat/Foundry를 활용한 유닛 테스트·배포 자동화') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (129, 21, 'Web3 라이브러리 및 프론트엔드 연동', 'Ethers.js/Web3.js를 활용한 지갑 연동 및 블록체인 데이터의 프론트엔드(React) 시각화') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (130, 21, 'DeFi 및 NFT 마켓플레이스 프로젝트', 'DEX(탈중앙화 거래소), NFT 민팅 사이트 등 실제 토크노믹스가 적용된 DApp 서비스 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (131, 21, '레이어2(L2) 및 오라클(Oracle) 활용', '확장성 해결을 위한 Polygon/Optimism 네트워크 배포 및 Chainlink를 활용한 오프체인 데이터 연동') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (132, 21, '실무 프로젝트', '최종 결과물을 만들고 서비스하는 단계') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (133, 23, '서비스 기획 방법론 및 프로세스 이해', '워터폴(Waterfall) 및 애자일(Agile) 방법론 비교 및 서비스 생애주기(Life Cycle) 이해') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (134, 23, '시장 조사 및 벤치마킹 분석', '경쟁사 분석, 포지셔닝 맵 작성 및 데스크 리서치를 통한 시장 기회 도출') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (135, 23, 'UX 리서치 및 사용자 경험 설계', '페르소나(Persona) 설정, 유저 저니 맵(Journey Map) 작성을 통한 사용자 니즈 발굴') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (136, 23, '정보구조(IA) 설계 및 유저 플로우 작성', '서비스 메뉴 구조도(IA) 설계 및 사용자 동선 최적화를 위한 플로우차트(Flowchart) 작성') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (137, 23, '요구사항 정의서(PRD) 및 기능 명세', '비즈니스 요구사항을 개발 가능한 단위로 구체화하는 PRD 작성') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (138, 23, '화면 설계서(SB) 및 와이어프레임 제작', 'UI 표준 정의 및 디스크립션(Description)이 포함된 상세 스토리보드(Storyboard) 작성') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (139, 23, '피그마(Figma) 활용 및 프로토타이핑', 'Figma 툴을 활용한 UI 컴포넌트 관리 및 개발/디자인 핸드오프를 위한 프로토타입 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (140, 23, '개발/디자인 협업을 위한 IT 문해력', '클라이언트/서버 구조, API, DB, 트랜잭션 등 개발자와의 소통을 위한 필수 IT 지식 함양') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (141, 23, '데이터 기반 의사결정 및 지표 관리', 'GA4, SQL 기초를 활용한 데이터 트래킹 및 핵심 성과 지표(KPI/OKR) 수립 전략') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (142, 23, 'MVP 기획 및 런칭 프로젝트', '최소 기능 제품(MVP) 기획부터 백로그 관리, 스프린트 운영을 포함한 실전 서비스 런칭') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (143, 24, '디지털 마케팅 개론 및 프레임워크', '마케팅의 본질 이해 및 페르소나 설정, 고객 여정 지도(Customer Journey Map) 설계') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (144, 24, 'IT/SW 시장 트렌드 및 비즈니스 모델', 'SaaS, 플랫폼, 앱 서비스 등 IT 비즈니스 유형별 수익 모델(BM) 분석 및 시장 조사') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (145, 24, '마케팅 퍼널(Funnel) 설계 전략', 'AARRR(획득-활성화-유지-매출-추천) 프레임워크 이해 및 단계별 핵심 지표(KPI) 설정') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (146, 24, '데이터 리터러시 및 엑셀 활용', '데이터 기반 의사결정을 위한 기초 통계 이해 및 엑셀/스프레드시트를 활용한 데이터 가공') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (147, 24, '퍼포먼스 마케팅 및 매체 운영', 'Meta(SNS), Google Ads, 검색광고(SA) 등 주요 매체별 광고 세팅 및 ROAS 최적화') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (148, 24, '콘텐츠 마케팅 및 SEO(검색엔진 최적화)', '테크니컬 SEO 원리 이해 및 전환을 유도하는 카피라이팅, 상세페이지 기획') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (149, 24, '그로스 해킹(Growth Hacking) 및 실험', '가설 수립 및 A/B 테스트 설계를 통한 UX/UI 개선 및 전환율 최적화(CRO)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (150, 24, 'CRM 마케팅 및 고객 리텐션', '이메일, 앱 푸시, 카카오 알림톡 등을 활용한 재방문 유도 및 이탈률 방어 전략') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (151, 24, '웹/앱 로그 분석 (GA/Amplitude)', 'Google Analytics 또는 Amplitude를 활용한 유저 행동 추적 및 이벤트 택소노미 설계') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (152, 24, '실전 마케팅 캠페인 및 성과 리포팅', '예산 설정부터 광고 집행, 성과 분석, 개선안 도출까지 포함된 풀사이클 캠페인 프로젝트') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (153, 25, '디자인 기초 이론 및 조형 원리', '타이포그래피, 컬러 시스템, 그리드(Grid) 레이아웃 등 시각 디자인의 핵심 원리 숙지') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (154, 25, '피그마(Figma) 핵심 및 심화 활용', '오토 레이아웃(Auto Layout), 컴포넌트, 베리어블 등 실무 필수 Figma 기능 마스터') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (155, 25, '그래픽 리소스 제작 (PS/AI)', '포토샵·일러스트레이터를 활용한 아이콘 제작, 이미지 보정 및 그래픽 에셋 디자인') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (156, 25, '웹/앱 환경 및 해상도의 이해', '반응형 웹의 브레이크 포인트 및 iOS/Android 모바일 OS별 해상도 가이드라인 학습') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (157, 25, 'UX 리서치 및 방법론', '데스크 리서치, 경쟁사 분석, 페르소나(Persona) 및 저니맵 설정을 통한 사용자 니즈 발굴') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (158, 25, '정보구조(IA) 및 와이어프레임', '서비스 메뉴 구조(IA) 설계 및 기획을 시각화하는 로우파이(Lo-Fi) 와이어프레임 작성') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (159, 25, '프로토타이핑 및 인터랙션', '화면 흐름을 검증하는 프로토타입 제작 및 마이크로 인터랙션(Smart Animate) 구현') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (160, 25, '디자인 시스템 구축 및 관리', '컬러, 폰트, UI 컴포넌트의 표준화 및 재사용 가능한 디자인 시스템 가이드라인 제작') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (161, 25, '반응형 웹 및 모바일 앱 프로젝트', 'PC, Tablet, Mobile 등 다양한 디바이스 환경에 최적화된 실전 UI 디자인 프로젝트 수행') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.curriculums (curriculum_id, category_id, curriculum_name, curriculum_desc) VALUES (162, 25, '실무 프로젝트', '최종 결과물을 만들고 서비스하는 단계') ON CONFLICT DO NOTHING;
SELECT setval('swcampus.curriculums_curriculum_id_seq', (SELECT COALESCE(MAX(curriculum_id), 1) FROM swcampus.curriculums));
