-- Auto-generated migration file: V9__seed_lecture_quals.sql
-- Generated at: 2025-12-17 10:28:24

INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (1, 1, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (2, 1, 'REQUIRED', '수료 후 즉시 취업이 가능한 미취업자(실업자)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (3, 1, 'REQUIRED', '대학 졸업 예정자(4학년) 및 졸업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (4, 1, 'PREFERRED', '정보통신/컴퓨터 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (5, 1, 'PREFERRED', '비전공자라도 개발에 대한 학습 의지가 뚜렷한 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (6, 1, 'PREFERRED', '프로그래밍 기초 지식 보유자.') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (7, 2, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (8, 2, 'REQUIRED', '훈련 기간 동안 성실히 참여 가능한 미취업자/졸업예정자.') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (9, 2, 'PREFERRED', '정보보호학과') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (10, 2, 'PREFERRED', '컴퓨터공학과 등 IT 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (11, 2, 'PREFERRED', '정보처리(산업)기사 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (12, 2, 'PREFERRED', '리눅스 마스터 등 서버 관련 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (13, 3, 'REQUIRED', '국민내일배움카드 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (14, 3, 'REQUIRED', '훈련 기간 동안 출석이 가능한 구직자(실업자)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (15, 3, 'REQUIRED', '대학 졸업 예정자.') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (16, 3, 'PREFERRED', 'IT 관련 전공자(컴퓨터공학 등)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (17, 3, 'PREFERRED', '정보처리기사/기능사 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (18, 3, 'PREFERRED', '자바 기초 문법 선행 학습자.') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (19, 4, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (20, 4, 'REQUIRED', '수료 후 취업 의지가 확고한 자.') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (21, 4, 'PREFERRED', '컴퓨터/정보통신 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (22, 4, 'PREFERRED', '리눅스(Linux) 기초 지식 보유자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (23, 4, 'PREFERRED', '정보처리기사/네트워크관리사 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (24, 5, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (25, 5, 'REQUIRED', '훈련에 전념할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (26, 5, 'PREFERRED', 'IT 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (27, 5, 'PREFERRED', '프로그래밍 언어(Java') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (28, 5, 'PREFERRED', 'Python 등) 학습 경험자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (29, 5, 'PREFERRED', '정보처리기사 자격증 소지자. 비전공자라도 논리적 사고력과 학습 의지가 강한 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (30, 6, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (31, 6, 'REQUIRED', '6개월 이상 장기 훈련 참여가 가능한 미취업자.') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (32, 6, 'PREFERRED', '컴퓨터/전자/기계공학 등 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (33, 6, 'PREFERRED', '프로그래밍(C언어') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (34, 6, 'PREFERRED', '파이썬) 기초 학습자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (35, 6, 'PREFERRED', '임베디드 및 로봇 분야 취업 의지가 확고한 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (36, 7, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (37, 7, 'REQUIRED', '훈련 기간 동안 성실히 참여할 수 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (38, 7, 'PREFERRED', '컴퓨터 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (39, 7, 'PREFERRED', '프로그래밍 기초 학습자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (40, 7, 'PREFERRED', '노코드/AI 툴 활용에 관심이 많은 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (41, 8, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (42, 8, 'REQUIRED', '6개월 이상의 장기 훈련에 성실히 참여할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (43, 8, 'PREFERRED', '기계/전자/컴퓨터공학 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (44, 8, 'PREFERRED', 'C++ 또는 Python 프로그래밍 기초 학습자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (45, 8, 'PREFERRED', '로봇 및 임베디드 분야 취업 희망자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (46, 9, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (47, 9, 'REQUIRED', '데이터 분석 및 AI 분야로 취업을 희망하는 미취업자.') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (48, 9, 'PREFERRED', '통계학/컴퓨터공학 등 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (49, 9, 'PREFERRED', 'Python 기초 문법 학습자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (50, 9, 'PREFERRED', '엑셀 활용 능력이 우수한 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (51, 10, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (52, 10, 'REQUIRED', '평일 오전 9시부터 오후 9시까지(하루 12시간) 몰입 학습이 가능한 자.') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (53, 10, 'PREFERRED', '비전공자라도 성장 의지가 강한 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (54, 10, 'PREFERRED', '팀 프로젝트 협업에 적극적인 자.') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (55, 11, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (56, 11, 'REQUIRED', '훈련 기간 동안 풀타임 학습이 가능한 자.') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (57, 11, 'PREFERRED', '디자인 관련 전공자 우대하나') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (58, 11, 'PREFERRED', '비전공자라도 스타트업 문화에 관심이 많고 주도적인 성향을 가진 사람을 선호') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (59, 12, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (60, 12, 'REQUIRED', '평일 9시~21시(하루 12시간) 몰입 학습이 가능한 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (61, 12, 'PREFERRED', '꼼꼼하고 논리적인 성격 소유자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (62, 12, 'PREFERRED', '반복적인 검증 과정을 끈기 있게 수행할 수 있는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (63, 12, 'PREFERRED', 'IT 비전공자지만 기술 직군으로 취업하고 싶은 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (64, 13, 'REQUIRED', '국민내일배움카드 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (65, 13, 'REQUIRED', '훈련 기간 성실 참여 가능한 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (66, 13, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (67, 13, 'PREFERRED', '자바 프로그래밍 기초 학습자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (68, 13, 'PREFERRED', '개발 도구(Tool) 및 최신 기술 습득에 거부감이 없는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (69, 14, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (70, 14, 'REQUIRED', '6개월간 평일 주 5일 훈련에 성실히 참여할 수 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (71, 14, 'PREFERRED', '컴퓨터공학/통계학 등 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (72, 14, 'PREFERRED', '정보처리기사/빅데이터분석기사 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (73, 14, 'PREFERRED', '프로그래밍(Java 또는 Python) 기초 지식 보유자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (74, 15, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (75, 15, 'REQUIRED', '6개월간 풀타임 교육 참여가 가능한 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (76, 15, 'PREFERRED', '컴퓨터공학/소프트웨어 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (77, 15, 'PREFERRED', 'Java 또는 Python 언어 입문자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (78, 15, 'PREFERRED', '최신 AI 기술을 웹 서비스에 접목해보고 싶은 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (79, 16, 'REQUIRED', '국민내일배움카드 발급 대상자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (80, 16, 'REQUIRED', '6개월간 훈련에 전념할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (81, 16, 'PREFERRED', '컴퓨터 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (82, 16, 'PREFERRED', '정보처리기사 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (83, 16, 'PREFERRED', '앱 개발에 관심이 있거나 기초적인 자바 학습 경험이 있는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (84, 17, 'REQUIRED', '국민내일배움카드 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (85, 17, 'REQUIRED', '훈련 기간(약 2개월) 동안 평일 9시~18시 풀타임 참여 가능한 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (86, 17, 'PREFERRED', '단기 심화 과정이므로 IT/통계 관련 전공자이거나') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (87, 17, 'PREFERRED', '파이썬/빅데이터 기초 교육을 이미 수료한 사람을 강력하게 우대') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (88, 18, 'REQUIRED', '국민내일배움카드 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (89, 18, 'REQUIRED', '약 6개월간 훈련에 집중할 수 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (90, 18, 'PREFERRED', '전기/전자/기계공학 또는 컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (91, 18, 'PREFERRED', '정보처리/전기/전자 관련 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (92, 19, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (93, 19, 'REQUIRED', '약 6개월간 평일 주 5일 훈련에 성실히 참여할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (94, 19, 'PREFERRED', '정보통신 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (95, 19, 'PREFERRED', '정보처리(산업)기사 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (96, 19, 'PREFERRED', '프로그래밍 기초 학습 경험이 있는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (97, 20, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (98, 20, 'REQUIRED', '6개월간 풀타임(주 5일) 학습이 가능한 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (99, 20, 'PREFERRED', '컴퓨터/정보보호 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (100, 20, 'PREFERRED', '네트워크 관리사/리눅스 마스터 등 기초 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (101, 21, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (102, 21, 'REQUIRED', '6개월간 훈련에 참여 가능한 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (103, 21, 'PREFERRED', '통계/산업공학/컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (104, 21, 'PREFERRED', 'SQL 및 Python 기초 지식 보유자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (105, 22, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (106, 22, 'REQUIRED', '평일 9시~21시(하루 12시간) 강도 높은 학습을 견딜 수 있는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (107, 22, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (108, 22, 'PREFERRED', 'C/C++ 언어 기초 학습자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (109, 22, 'PREFERRED', '게임 개발에 대한 열정이 남다른 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (110, 23, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (111, 23, 'REQUIRED', '평일 9시~18시 풀타임 학습이 가능한 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (112, 23, 'PREFERRED', '컴퓨터공학/인공지능 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (113, 23, 'PREFERRED', 'Python 프로그래밍 및 딥러닝 기초 지식 보유자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (114, 24, 'REQUIRED', '국민내일배움카드 발급 대상자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (115, 24, 'REQUIRED', '약 6개월간 훈련에 집중할 수 있는 미취업자 및 졸업예정자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (116, 24, 'PREFERRED', '컴퓨터공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (117, 24, 'PREFERRED', '전자공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (118, 24, 'PREFERRED', '통계학 등 관련 전공자. 혹은 데이터 분석이나 IoT 기술에 흥미가 있고 기초 학습 경험이 있는 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (119, 25, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (120, 25, 'REQUIRED', '부산/경남 지역 거주자(지역인재 우대 가능성 있음)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (121, 25, 'REQUIRED', '6개월 풀타임 학습 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (122, 25, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (123, 25, 'PREFERRED', '자바 프로그래밍 기초가 되어 있는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (124, 26, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (125, 26, 'REQUIRED', '장기 훈련에 참여 가능한 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (126, 26, 'PREFERRED', '컴퓨터공학/게임공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (127, 26, 'PREFERRED', 'C/C++ 언어 기초 학습자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (128, 26, 'PREFERRED', '게임 개발 분야 취업 의지가 확고한 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (129, 27, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (130, 27, 'REQUIRED', '6개월간 성실히 훈련에 참여할 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (131, 27, 'PREFERRED', '컴퓨터 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (132, 27, 'PREFERRED', '혹은 비전공자라도 IT 기초 지식(컴퓨터활용능력 등)이 있거나 개발자 취업 의지가 확고한 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (133, 28, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (134, 28, 'REQUIRED', '6개월간 성실히 훈련에 참여할 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (135, 28, 'PREFERRED', '컴퓨터/통계/데이터 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (136, 28, 'PREFERRED', 'SQL 자격증(SQLD 등) 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (137, 28, 'PREFERRED', '데이터베이스에 관심이 많은 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (138, 29, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (139, 29, 'REQUIRED', '6개월간 풀타임 교육 참여 가능한 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (140, 29, 'PREFERRED', '기계/전자/컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (141, 29, 'PREFERRED', '프로그래밍(Python/C++) 기초가 있는 자. 창업에 관심이 있거나 기획력이 있는 비전공자도 환영') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (142, 30, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (143, 30, 'PREFERRED', 'Python 기초 지식이 있거나') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (144, 30, 'PREFERRED', '개발 경험이 있지만 최신 기술(AI') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (145, 30, 'PREFERRED', 'DevOps)을 보강하고 싶은 전공자/경력자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (146, 31, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (147, 31, 'REQUIRED', '게임 개발에 몰입할 수 있는 미취업자.') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (148, 31, 'PREFERRED', '게임 기획이나 개발 경험이 있는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (149, 31, 'PREFERRED', '자신만의 게임을 만들어보고 싶은 강한 열정을 가진 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (150, 32, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (151, 32, 'REQUIRED', '6개월간 풀타임 학습이 가능한 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (152, 32, 'PREFERRED', '디자인 감각이 있거나 UI/UX에 관심이 많은 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (153, 32, 'PREFERRED', 'HTML/CSS 기초 코딩 경험자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (154, 32, 'PREFERRED', '내 손으로 앱을 만들어보고 싶은 열정이 있는 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (155, 33, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (156, 33, 'REQUIRED', '6개월간 성실하게 훈련에 참여할 수 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (157, 33, 'PREFERRED', '컴퓨터공학/정보통신 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (158, 33, 'PREFERRED', '프로그래밍(Java 등) 기초 학습 경험자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (159, 33, 'PREFERRED', '정보처리기사/산업기사 자격증 소지자. 데이터를 활용한 웹 서비스 개발에 관심이 많은 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (160, 34, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (161, 34, 'REQUIRED', '약 6개월간 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (162, 34, 'PREFERRED', '컴퓨터/정보보호 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (163, 34, 'PREFERRED', '정보처리(산업)기사 자격증 소지자. 보안이나 자동화 기술에 관심이 있는 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (164, 35, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (165, 35, 'REQUIRED', '6개월간 풀타임 학습이 가능한 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (166, 35, 'PREFERRED', '정보통신/전자공학 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (167, 35, 'PREFERRED', '기계 제어나 회로에 관심이 있는 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (168, 36, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (169, 36, 'REQUIRED', '수학적 사고력과 끈기가 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (170, 36, 'PREFERRED', '컴퓨터공학/수학/물리학 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (171, 36, 'PREFERRED', 'C언어 포인터 개념을 이해하고 있는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (172, 37, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (173, 37, 'REQUIRED', '6개월간 풀타임 학습 가능한 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (174, 37, 'PREFERRED', '컴퓨터공학/정보통신공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (175, 37, 'PREFERRED', '네트워크관리사/리눅스마스터 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (176, 38, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (177, 38, 'REQUIRED', '6개월간 풀타임(주 5일) 학습이 가능한 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (178, 38, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (179, 38, 'PREFERRED', '정보처리기사 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (180, 39, 'REQUIRED', '국민내일배움카드 소지자. (중요) Python 프로그래밍 기초가 있는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (181, 39, 'PREFERRED', '컴퓨터공학/인공지능/통계학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (182, 39, 'PREFERRED', '혹은 이전에 AI 기초 과정을 수료했지만 비전 AI 포트폴리오가 부족하다고 느끼는 수료생') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (183, 40, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (184, 40, 'REQUIRED', '6개월간 풀타임 학습이 가능한 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (185, 40, 'PREFERRED', '컴퓨터공학/정보통신 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (186, 40, 'PREFERRED', '정보처리(산업)기사 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (187, 40, 'PREFERRED', '리눅스(Linux) 기초 지식이 있는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (188, 41, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (189, 41, 'REQUIRED', '6개월 이상 성실히 훈련에 참여할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (190, 41, 'PREFERRED', '컴퓨터공학 등 IT 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (191, 41, 'PREFERRED', '혹은 비전공자라도 IT 분야로의 취업 의지가 확고하고 기초적인 컴퓨터 활용 능력이 있는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (192, 42, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (193, 42, 'REQUIRED', '약 6개월간 장기 훈련에 성실히 참여할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (194, 42, 'PREFERRED', '컴퓨터공학/정보통신 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (195, 42, 'PREFERRED', '정보처리기사 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (196, 43, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (197, 43, 'REQUIRED', '6개월간 성실히 훈련에 참여할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (198, 43, 'PREFERRED', '컴퓨터 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (199, 43, 'PREFERRED', '혹은 비전공자라도 IT 분야 취업 의지가 확고한 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (200, 44, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (201, 44, 'REQUIRED', '약 6개월간 풀타임 훈련 참여 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (202, 44, 'PREFERRED', '컴퓨터공학/정보통신/통계학 관련 전공자. 단순 코딩을 넘어 데이터를 다루는 것에 흥미가 있는 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (203, 45, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (204, 45, 'REQUIRED', '6개월간 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (205, 45, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (206, 45, 'PREFERRED', '정보처리 기사/산업기사 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (207, 46, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (208, 46, 'REQUIRED', '약 6개월간 훈련에 집중할 수 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (209, 46, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (210, 46, 'PREFERRED', '정보처리 관련 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (211, 47, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (212, 47, 'REQUIRED', '웹툰 및 콘텐츠 분야 취업 희망자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (213, 47, 'PREFERRED', '미술/디자인/문예창작 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (214, 48, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (215, 48, 'REQUIRED', '6개월간 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (216, 48, 'PREFERRED', '시각적인 결과물을 만드는 것을 좋아하는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (217, 48, 'PREFERRED', '디자인 감각이 있거나 UI/UX에 관심이 많은 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (218, 49, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (219, 49, 'REQUIRED', '6개월간 고난도 기술 학습을 소화할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (220, 49, 'PREFERRED', '컴퓨터공학/소프트웨어 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (221, 49, 'PREFERRED', '정보처리기사 소지자. "서버 구조와 아키텍처에 관심이 많은" 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (222, 50, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (223, 50, 'REQUIRED', '다양한 툴(Tool) 학습에 거부감이 없는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (224, 50, 'PREFERRED', '시각디자인/영상/미디어 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (225, 51, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (226, 51, 'REQUIRED', '영상 콘텐츠 제작에 흥미가 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (227, 51, 'PREFERRED', '영상/영화/문예창작 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (228, 52, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (229, 52, 'REQUIRED', '훈련 기간 성실히 참여할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (230, 52, 'PREFERRED', '컴퓨터공학 전공자 우대하나') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (231, 52, 'PREFERRED', '다양한 언어를 배우는 것에 두려움이 없는 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (232, 53, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (233, 53, 'REQUIRED', '하드웨어와 소프트웨어 융합에 관심 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (234, 53, 'PREFERRED', '전기/전자/정보통신/컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (235, 54, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (236, 54, 'REQUIRED', '6개월간 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (237, 54, 'PREFERRED', '컴퓨터 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (238, 54, 'PREFERRED', '프로그래밍 기초 학습자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (239, 55, 'REQUIRED', '국민내일배움카드 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (240, 55, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (241, 55, 'PREFERRED', 'AWS 자격증(SAA 등) 준비생') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (242, 55, 'PREFERRED', '빠르게 포트폴리오를 완성하고 싶은 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (243, 56, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (244, 56, 'REQUIRED', '6개월간 풀타임으로 프로젝트 수행이 가능한 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (245, 56, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (246, 56, 'PREFERRED', '혹은 비전공자라도 기초 코딩 지식이 있고 능동적인 커뮤니케이션이 가능한 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (247, 57, 'REQUIRED', '국민내일배움카드 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (248, 57, 'PREFERRED', '웹 개발 프로젝트 경험자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (249, 57, 'PREFERRED', '정보처리기사 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (250, 58, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (251, 58, 'REQUIRED', '6개월 이상의 고강도 훈련을 견딜 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (252, 58, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (253, 58, 'PREFERRED', '자바 프로그래밍 기초 학습자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (254, 59, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (255, 59, 'REQUIRED', '6개월간 성실히 훈련에 참여할 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (256, 59, 'PREFERRED', '컴퓨터공학/인공지능/언어학 관련 전공자. "사람과 대화하는 서비스를 만들어보고 싶은" 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (257, 60, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (258, 60, 'REQUIRED', '6개월간 대전 중구(대흥동)로 통학하며 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (259, 60, 'PREFERRED', '컴퓨터공학/정보통신 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (260, 61, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (261, 61, 'REQUIRED', '6개월간 부산 지역에서 통학하며 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (262, 61, 'PREFERRED', '컴퓨터공학/정보통신 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (263, 61, 'PREFERRED', '정보처리기사 자격증 소지자. 롯데 그룹사 및 협력사 취업을 희망하는 자. 비전공자라도 개발에 대한 열정과 성실함을 갖춘 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (264, 62, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (265, 62, 'REQUIRED', '3D 콘텐츠 제작 및 VR 분야 취업 희망자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (266, 62, 'PREFERRED', '디자인/영상/게임 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (267, 62, 'PREFERRED', '3D 툴(Blender') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (268, 62, 'PREFERRED', 'Max 등) 기초 사용 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (269, 63, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (270, 63, 'REQUIRED', '6개월간 고난도 기술 학습에 전념할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (271, 63, 'PREFERRED', '컴퓨터공학/정보보호학/수학 관련 전공자. 핀테크') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (272, 63, 'PREFERRED', '보안') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (273, 63, 'PREFERRED', '블록체인 산업에 관심이 많고 논리적 사고력이 뛰어난 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (274, 64, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (275, 64, 'REQUIRED', '6개월 이상의 장기 훈련을 완주할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (276, 64, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (277, 64, 'PREFERRED', '혹은 비전공자라도 IT 기초 학습 경험이 있는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (278, 65, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (279, 65, 'REQUIRED', '콘텐츠 제작과 기획에 흥미가 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (280, 65, 'PREFERRED', '디자인/영상/미디어 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (281, 66, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (282, 66, 'REQUIRED', '6개월간 훈련에 성실히 참여할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (283, 66, 'PREFERRED', '컴퓨터공학/통계학 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (284, 67, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (285, 67, 'REQUIRED', '6개월간 서울(가산/강남 등 지정 교육장) 통학이 가능한 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (286, 67, 'PREFERRED', '전기/전자/컴퓨터/통신공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (287, 68, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (288, 68, 'REQUIRED', '6개월간 훈련에 몰입할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (289, 68, 'PREFERRED', '게임공학/멀티미디어 관련 전공자. C언어 등 프로그래밍 기초가 있거나') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (290, 68, 'PREFERRED', 'Unity 엔진을 다뤄본 경험이 있는 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (291, 69, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (292, 69, 'REQUIRED', '6개월간 훈련에 전념할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (293, 69, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (294, 69, 'PREFERRED', '정보처리 관련 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (295, 70, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (296, 70, 'REQUIRED', '6개월간 풀타임(주 5일') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (297, 70, 'REQUIRED', '일 8시간) 학습이 가능한 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (298, 70, 'PREFERRED', '컴퓨터공학/통계학/수학 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (299, 70, 'PREFERRED', 'Python 프로그래밍 기초 학습자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (300, 71, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (301, 71, 'REQUIRED', '새로운 AI 툴 학습에 거부감이 없는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (302, 71, 'PREFERRED', '영상 편집 기초가 있는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (303, 71, 'PREFERRED', '디자인/예술 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (304, 72, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (305, 72, 'REQUIRED', '6개월 이상 장기 훈련에 성실히 참여할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (306, 72, 'PREFERRED', '컴퓨터공학/통계학/수학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (307, 73, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (308, 73, 'REQUIRED', '6개월 이상의 고난도 기술 교육을 이수할 수 있는 미취업자.') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (309, 73, 'PREFERRED', '정보보호학과/컴퓨터공학과 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (310, 73, 'PREFERRED', '정보보안기사/네트워크관리사 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (311, 74, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (312, 74, 'REQUIRED', '6개월간 게임 개발에 몰입할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (313, 74, 'PREFERRED', '게임공학/컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (314, 74, 'PREFERRED', '프로그래밍 기초가 있는 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (315, 75, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (316, 75, 'REQUIRED', '6개월간 훈련에 전념할 수 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (317, 75, 'PREFERRED', '비전공자 강력 추천') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (318, 76, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (319, 76, 'REQUIRED', '6개월간 훈련에 집중할 수 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (320, 76, 'PREFERRED', '컴퓨터공학 전공자뿐만 아니라 산업공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (321, 76, 'PREFERRED', '기계공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (322, 76, 'PREFERRED', '전자공학 등 제조업 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (323, 77, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (324, 77, 'REQUIRED', '6개월간 훈련에 참여 가능한 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (325, 77, 'PREFERRED', '컴퓨터/경영정보 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (326, 78, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (327, 78, 'REQUIRED', '6개월간 몰입 학습이 가능한 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (328, 78, 'PREFERRED', '게임공학/컴퓨터공학 전공자. C언어 기초가 있는 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (329, 79, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (330, 79, 'REQUIRED', '6개월간 훈련에 집중할 수 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (331, 79, 'PREFERRED', '컴퓨터공학 전공자뿐만 아니라 산업공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (332, 79, 'PREFERRED', '기계공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (333, 79, 'PREFERRED', '전자공학 등 제조업 관련 전공자도 매우 선호') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (334, 80, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (335, 80, 'REQUIRED', '6개월간 훈련에 집중할 수 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (336, 80, 'PREFERRED', '컴퓨터공학 전공자뿐만 아니라 산업공학(IE)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (337, 80, 'PREFERRED', '경영과학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (338, 80, 'PREFERRED', '수학/통계학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (339, 81, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (340, 81, 'PREFERRED', '컴퓨터공학/통계학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (341, 81, 'PREFERRED', '웹 개발 경험이 있거나 데이터 분석 기초 과정을 수료한 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (342, 82, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (343, 82, 'REQUIRED', '6개월간 풀타임 학습 가능한 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (344, 82, 'PREFERRED', '생명공학/간호학/보건행정학 등 바이오 메디컬 관련 전공자(도메인 지식 보유). 혹은 컴퓨터공학 전공자 중 헬스케어 분야 진출 희망자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (345, 83, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (346, 83, 'REQUIRED', '마케팅/기획 분야 취업 희망자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (347, 83, 'PREFERRED', '경영/경제/통계/광고홍보 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (348, 84, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (349, 84, 'REQUIRED', '6개월간 훈련에 전념할 수 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (350, 84, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (351, 85, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (352, 85, 'REQUIRED', '6개월간 훈련에 전념할 수 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (353, 85, 'PREFERRED', '컴퓨터공학 전공자. "백엔드 로직 구현에 흥미가 있고') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (354, 85, 'PREFERRED', 'AI 기술을 접목해보고 싶은" 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (355, 86, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (356, 86, 'REQUIRED', '6개월간 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (357, 86, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (358, 87, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (359, 87, 'REQUIRED', '6개월간 훈련에 전념할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (360, 87, 'PREFERRED', '컴퓨터공학/통계학/정보통신 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (361, 88, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (362, 88, 'REQUIRED', '시각적인 결과물을 만드는 것에 흥미가 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (363, 88, 'PREFERRED', '디자인 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (364, 89, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (365, 89, 'PREFERRED', '이공계 전공자 필수 권장') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (366, 90, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (367, 90, 'REQUIRED', '6개월간 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (368, 90, 'PREFERRED', '컴퓨터공학/통계학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (369, 91, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (370, 91, 'REQUIRED', '6개월간 훈련 참여 가능한 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (371, 91, 'PREFERRED', '컴퓨터/디자인/지리정보(GIS) 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (372, 92, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (373, 92, 'REQUIRED', '6개월간 풀타임 학습 가능한 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (374, 92, 'PREFERRED', '정보통신/컴퓨터공학 전공자. 네트워크관리사') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (375, 92, 'PREFERRED', '리눅스마스터 자격증 소지자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (376, 93, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (377, 93, 'REQUIRED', '게임 제작의 전 과정(A to Z)을 경험해보고 싶은 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (378, 93, 'PREFERRED', '게임/멀티미디어 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (379, 94, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (380, 94, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (381, 94, 'PREFERRED', '알고리즘 및 자료구조 기초 지식 보유자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (382, 95, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (383, 95, 'REQUIRED', '6개월간 학습에 전념 가능한 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (384, 95, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (385, 95, 'PREFERRED', '논리적 사고력이 뛰어난 비전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (386, 96, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (387, 96, 'REQUIRED', '6개월간 훈련에 몰입할 수 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (388, 96, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (389, 97, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (390, 97, 'REQUIRED', '6개월간 고강도 학습에 집중할 수 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (391, 97, 'PREFERRED', '전자/전기/기계/컴퓨터공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (392, 97, 'PREFERRED', '로봇공학 등 이공계 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (393, 98, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (394, 98, 'REQUIRED', '영상 콘텐츠 제작에 열정이 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (395, 98, 'PREFERRED', '시각 디자인/영상 관련 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (396, 99, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (397, 99, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (398, 100, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (399, 100, 'PREFERRED', 'Python 프로그래밍 경험이 있으며') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (400, 100, 'PREFERRED', '생명 현상 및 의학 분야에 대한 학습 의지가 높은 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (401, 101, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (402, 101, 'REQUIRED', '6개월간 집중 학습이 가능한 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (403, 101, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (404, 102, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (405, 102, 'PREFERRED', '컴퓨터공학 전공자. 보안') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (406, 102, 'PREFERRED', '금융(Fintech)') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (407, 102, 'PREFERRED', '분산 시스템에 관심이 많고 논리적 사고력이 뛰어난 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (408, 103, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (409, 103, 'PREFERRED', '컴퓨터공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (410, 103, 'PREFERRED', '통계학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (411, 103, 'PREFERRED', '수학 등 이공계열 전공자. 데이터를 통해 가치를 창출하는 것에 흥미를 느끼는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (412, 104, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (413, 104, 'PREFERRED', 'Python 및 수학/통계학 기초가 탄탄하며') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (414, 104, 'PREFERRED', '헬스케어 산업에 대한 이해와 열정이 높은 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (415, 105, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (416, 105, 'PREFERRED', '컴퓨터공학/소프트웨어 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (417, 106, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (418, 106, 'REQUIRED', '6개월간 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (419, 106, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (420, 107, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (421, 107, 'PREFERRED', '정보보호학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (422, 107, 'PREFERRED', '컴퓨터공학 전공자. 정보처리기사/정보보안기사 필기 합격자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (423, 108, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (424, 108, 'REQUIRED', '6개월 이상의 장기 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (425, 108, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (426, 109, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (427, 109, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (428, 109, 'PREFERRED', '혹은 React 기초 과정을 수료했거나 코딩 테스트를 통과할 수 있는 논리적 사고력의 보유자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (429, 110, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (430, 110, 'PREFERRED', '통계학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (431, 110, 'PREFERRED', '수학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (432, 110, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (433, 111, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (434, 111, 'PREFERRED', '기본적인 전기 회로 및 시퀀스 제어 지식이 있는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (435, 112, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (436, 112, 'PREFERRED', '컴퓨터공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (437, 112, 'PREFERRED', '통계학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (438, 112, 'PREFERRED', '인공지능 관련 전공자. 언어 데이터를 다루는 것에 흥미가 있고') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (439, 112, 'PREFERRED', '새로운 AI 기술에 대한 학습 열의가 높은 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (440, 113, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (441, 113, 'PREFERRED', '디자인 또는 IT 분야에 관심이 있고') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (442, 113, 'PREFERRED', 'JavaScript 기초 문법에 대한 이해가 있는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (443, 114, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (444, 114, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (445, 115, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (446, 115, 'PREFERRED', '컴퓨터공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (447, 115, 'PREFERRED', '산업공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (448, 115, 'PREFERRED', '물류 관련 전공자. 제조업 또는 물류/SCM 분야에 대한 관심이 높은 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (449, 116, 'REQUIRED', '고용보험에 가입된 재직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (450, 116, 'PREFERRED', 'IT 개발 또는 데이터 분석 경력이 $2\\sim3$년 이상이며') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (451, 116, 'PREFERRED', 'AI 기술을 소속 조직의 업무에 통합하고자 하는 명확한 목표를 가진 자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (452, 117, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (453, 117, 'REQUIRED', '6개월 이상의 장기 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (454, 117, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (455, 118, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (456, 118, 'REQUIRED', '6개월 이상의 장기 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (457, 118, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (458, 119, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (459, 119, 'REQUIRED', '게임/XR 개발에 대한 높은 열정이 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (460, 119, 'PREFERRED', '컴퓨터공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (461, 119, 'PREFERRED', '게임공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (462, 119, 'PREFERRED', '소프트웨어 전공자. 수학/물리적 개념 이해가 빠르고') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (463, 119, 'PREFERRED', '3D 환경에 대한 흥미가 높은 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (464, 120, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (465, 120, 'PREFERRED', 'C/C++ 또는 Python 프로그래밍 경험이 있으며') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (466, 120, 'PREFERRED', '제어 공학 또는 임베디드 시스템에 대한 이해가 있는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (467, 121, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (468, 121, 'PREFERRED', '컴퓨터공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (469, 121, 'PREFERRED', '게임공학 전공자. 알고리즘 및 자료구조에 대한 이해가 높고') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (470, 121, 'PREFERRED', '개발 직무로 명확히 목표를 설정한 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (471, 122, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (472, 122, 'REQUIRED', '6개월 이상의 장기 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (473, 122, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (474, 123, 'REQUIRED', '고용보험에 가입된 재직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (475, 123, 'PREFERRED', '2~3년 이상 경력의 현직 개발자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (476, 123, 'PREFERRED', '데이터 분석가 또는 AI 관련 프로젝트 관리자. Python 프로그래밍 및 선형대수/통계학 기초 지식이 필수') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (477, 124, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (478, 124, 'REQUIRED', '6개월 이상의 장기 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (479, 124, 'PREFERRED', '컴퓨터공학/소프트웨어 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (480, 125, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (481, 125, 'REQUIRED', '6개월 이상의 장기 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (482, 125, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (483, 126, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (484, 126, 'PREFERRED', '언론학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (485, 126, 'PREFERRED', '사회학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (486, 126, 'PREFERRED', '통계학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (487, 126, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (488, 127, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (489, 127, 'REQUIRED', '6개월 이상의 장기 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (490, 127, 'PREFERRED', '컴퓨터공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (491, 127, 'PREFERRED', '전자공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (492, 127, 'PREFERRED', '제어계측공학 등 하드웨어 및 소프트웨어 융합 분야에 관심이 높은 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (493, 128, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (494, 128, 'PREFERRED', '통계학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (495, 128, 'PREFERRED', '수학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (496, 128, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (497, 129, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (498, 129, 'REQUIRED', '6개월 이상의 장기 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (499, 129, 'PREFERRED', '컴퓨터공학 전공자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (500, 130, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (501, 130, 'REQUIRED', '6개월 이상의 장기 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (502, 130, 'PREFERRED', '영상') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (503, 130, 'PREFERRED', '디자인') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (504, 130, 'PREFERRED', '미디어 관련 분야에 관심이 있거나') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (505, 130, 'PREFERRED', '창의적인 콘텐츠 제작에 흥미를 느끼는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (506, 131, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (507, 131, 'PREFERRED', '디자인 및 개발 양쪽에 흥미가 있으며') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (508, 131, 'PREFERRED', '최신 프론트엔드 기술을 활용하여 고품질 웹 서비스를 만들고자 하는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (509, 132, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (510, 132, 'PREFERRED', '컴퓨터공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (511, 132, 'PREFERRED', '정보통신공학 등 이공계열 전공자. 서버 관리 및 시스템 운영에 흥미를 느끼는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (512, 133, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (513, 133, 'REQUIRED', '게임 기획에 대한 높은 열정이 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (514, 133, 'PREFERRED', '문예 창작') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (515, 133, 'PREFERRED', '디자인') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (516, 133, 'PREFERRED', '심리학 등 인문/사회 계열 전공자. 논리적 사고력과 뛰어난 문서 작성 및 커뮤니케이션 능력이 있는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (517, 134, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (518, 134, 'PREFERRED', '컴퓨터공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (519, 134, 'PREFERRED', '로봇공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (520, 134, 'PREFERRED', '기계공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (521, 134, 'PREFERRED', '전자공학 등 이공계 전공자. 복잡한 제어 시스템 개발에 흥미를 느끼는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (522, 135, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (523, 135, 'PREFERRED', '컴퓨터공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (524, 135, 'PREFERRED', '통계학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (525, 135, 'PREFERRED', '인공지능 관련 전공자. 자연어 처리') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (526, 135, 'PREFERRED', '음성 인식 등 언어 데이터에 흥미가 있는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (527, 136, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (528, 136, 'REQUIRED', '6개월 이상의 장기 훈련에 집중할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (529, 136, 'PREFERRED', '논리적 사고력과 뛰어난 문제 해결 능력을 가진 분. 프론트엔드 개발에 대한 명확한 목표를 가진 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (530, 137, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (531, 137, 'REQUIRED', '장기간의 풀스택 학습에 전념할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (532, 137, 'PREFERRED', '컴퓨터공학 전공자. 논리적인 시스템 설계와 대규모 데이터 처리에 흥미를 느끼는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (533, 138, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (534, 138, 'PREFERRED', '기계공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (535, 138, 'PREFERRED', '로봇공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (536, 138, 'PREFERRED', '산업공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (537, 138, 'PREFERRED', '컴퓨터공학 전공자. 설계와 개발을 융합하여 가상 세계를 통한 현실 문제 해결에 흥미를 느끼는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (538, 139, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (539, 139, 'REQUIRED', '장기간의 자바 풀스택 학습에 집중할 수 있는 구직자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (540, 139, 'PREFERRED', '컴퓨터공학 전공자. 대용량 트래픽 처리와 시스템 아키텍처 설계에 흥미를 느끼는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (541, 140, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (542, 140, 'PREFERRED', '컴퓨터공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (543, 140, 'PREFERRED', '통계학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (544, 140, 'PREFERRED', '인공지능') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (545, 140, 'PREFERRED', '언어학 관련 전공자. 텍스트 데이터를 분석하고 의미를 도출하는 일에 흥미를 느끼는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (546, 141, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (547, 141, 'PREFERRED', '컴퓨터공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (548, 141, 'PREFERRED', '정보통신학 전공자. 최신 AI 기술을 활용하여 실제 작동하는 웹/앱 서비스를 만들어 보고 싶은 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (549, 142, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (550, 142, 'PREFERRED', '정보보호학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (551, 142, 'PREFERRED', '컴퓨터공학 전공자. 시스템의 안정적인 운영 및 문제 해결에 흥미를 느끼는 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (552, 143, 'REQUIRED', '국민내일배움카드 발급 가능자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (553, 143, 'REQUIRED', '장기간의 학습과 취업 준비에 전념할 수 있는 미취업자') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (554, 143, 'PREFERRED', '시스템의 작동 원리와 안정적인 서버 운영에 흥미를 느끼는 분. 자바/리액트 학습을 통해 개발 커리어를 확고히 하고 싶은 분') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (555, 144, 'REQUIRED', '국민내일배움카드 발급 가능자. 3D 공간에 대한 이해와 프로그래밍 학습에 대한 열의') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (556, 144, 'PREFERRED', '컴퓨터공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (557, 144, 'PREFERRED', '게임공학') ON CONFLICT DO NOTHING;
INSERT INTO swcampus.lecture_quals (qual_id, lecture_id, type, text) VALUES (558, 144, 'PREFERRED', '미디어 디자인 관련 전공자') ON CONFLICT DO NOTHING;
