name: Build & Push (Release)

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag
        id: tag
        run: echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build & Push
        run: |
          docker build -t ghcr.io/sw-campus/sw-campus-server:${{ steps.tag.outputs.tag }} .
          docker push ghcr.io/sw-campus/sw-campus-server:${{ steps.tag.outputs.tag }}
